# Generated by Django 2.0 on 2018-01-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shimons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
