# Generated by Django 2.0 on 2018-01-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shimons', '0002_remove_userprofile_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardPosts',
            new_name='DashboardPost',
        ),
    ]
