# Generated by Django 2.0 on 2018-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shimons', '0004_auto_20180103_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='name',
            field=models.CharField(default='req_<built-in function id>', max_length=128),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='jar_path',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='src_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
